# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 239f3b0da695a0e09e21a285f5f1ec4662d1eecf1d9b5eba701d4686157b1851938c135bce64c7f705f2b94b2ac05ea7967a379b5daf8bfe30638f3e6e30d1f0

test:
  secret_key_base: 16096a37782607e817bfee355f07e3f301452165384a39dec80f0406cdfdbabf6343d01a3b07abb68050a7450fd9a29a544d75cfd7211faef4adc42c88d30ff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
